### ISSUE TITLE
UI atravessa chat popup tooltip

### ISSUE THREAD

**Issue by vcwild** [iaurg/42-transcendence#112]
## Descrição

A interface do chat flutuante atravessa os limites do componente.

![image](https://github.com/iaurg/42-transcendence/assets/49621396/cec5cd7f-324f-4f7a-9aa7-274b4a5f542f)

**Comment by iaurg** [comment]
Fixed with ...
<img width="555" alt="image" src="https://github.com/iaurg/42-transcendence/assets/11761170/6eb940f9-2532-42f5-96ed-6146b02b2b4b">
