### ISSUE TITLE
Chat component reloads when clicking history

### ISSUE THREAD

**Issue by vcwild** [iaurg/42-transcendence#125]
## Description

Chat component reloads when clicking history.

![image](https://github.com/iaurg/42-transcendence/assets/49621396/5682c970-069a-4e7b-b3b1-ecd16eeacf0c)

**Comment by iaurg** [comment]
hm, talvez esteja mudando de página de forma forçada, vou validar aqui

**Comment by vcwild** [comment]
o @GuiMartinelli viu tambem que o user fica offline no componente de status
