### ISSUE TITLE
[UX] Nome de chat muito grande invadindo components

### ISSUE THREAD

**Issue by iaurg** [iaurg/42-transcendence#146]
<img width="309" alt="image" src="https://github.com/iaurg/42-transcendence/assets/11761170/1d1a8eb5-9bb4-4baa-9a96-dd67dda926f4">

**Comment by vcwild** [comment]
Resolved 
![image](https://github.com/iaurg/42-transcendence/assets/49621396/74250514-1a15-4e80-bb7d-7617e38698da)
