### ISSUE TITLE
Draw the project deployment workflow

### ISSUE THREAD

**Issue by iaurg** [iaurg/42-transcendence#2]
**Modelos:**

https://excalidraw.com/#room=65733053a2453906890f,U0koJjBm_okx7N2PbnrWGQ

https://excalidraw.com/#room=fb6fae1d831e045fdafd,YYe9KxHGi8MoupYT0ZtAYQ

![Image](https://user-images.githubusercontent.com/11761170/233813531-ff10d259-9dad-47dd-86f3-01416d08d081.png)

 - Set up the development environment: Install and configure the required software tools and libraries, including NestJS, TypeScript framework, and PostgreSQL database.

    Design the user interface: Create wireframes and mockups of the website's user interface, including the game interface, chat, user profiles, and login page.
 - Implement the user authentication: Integrate the OAuth system of 42 intranet for user login, and implement password hashing and server-side validation for forms and user input.

 - Implement user account features: Allow users to choose a unique name and upload an avatar, enable two-factor authentication, and allow users to add friends and view their profiles and match history.
 - Design and implement the chat functionality: Create chat rooms with public, private, and password-protected channels, allow direct messages between users, and implement blocking, kicking, and muting features for channel administrators.

 - Design and implement the game functionality: Create a responsive Pong game with matchmaking, customization options, and multiplayer capabilities.

 - Test the website thoroughly: Ensure the website is compatible with the latest stable versions of Google Chrome and one additional web browser, and test for security vulnerabilities, errors, and warnings.

 - Deploy the website: Launch the website with a single call to docker-compose up --build, and ensure it is running smoothly on the production environment.

 - Maintenance and updates: Monitor the website for issues and updates, and ensure it remains up-to-date with the latest stable versions of the software tools and libraries used in the project.

**Comment by vcwild** [comment]
@caio-vinicius Define this task as you see fit, change it to comply with the design that you are developing
