### ISSUE TITLE
Chat exception congela server

### ISSUE THREAD

**Issue by iaurg** [iaurg/42-transcendence#88]
Ao logar no front com um token inválido o back trava neste bloco:
<img width="752" alt="image" src="https://github.com/iaurg/42-transcendence/assets/11761170/6fad94ad-e28a-48ef-8272-b551a27a9083">

Aparentemente precisa de alguma tratativa nesse exception para que ele continue e retorne o erro para o front

**Comment by iaurg** [comment]
Parece que todo exception trava o server
<img width="487" alt="image" src="https://github.com/iaurg/42-transcendence/assets/11761170/c0a9ac94-1271-45ff-9724-97cb9c703c9a">

Precisamos analisar uma forma de disparar exception que não trava o fluxo do servidor

**Comment by vcwild** [comment]
Conseguimos alguma condição de contorno pra essas exceptions? Temos alguns throw do server e umas exceções não lidadas que poderíamos usar um catch que só deixa elas rolarem sem levantar um erro

**Comment by iaurg** [comment]
> Conseguimos alguma condição de contorno pra essas exceptions? Temos alguns throw do server e umas exceções não lidadas que poderíamos usar um catch que só deixa elas rolarem sem levantar um erro

Ainda não encontrei nada que deixe isso passar, vou puxar um PR específico para isso pois travou no server em prod esse

**Comment by vcwild** [comment]
Os congelamentos foram corrigidos usando Promises
