### ISSUE TITLE
Analisar erro de rede: Pending 

### ISSUE THREAD

**Issue by iaurg** [iaurg/42-transcendence#96]
Já tentei de várias formas ajustar um erro que retorna no front quando faz consulta para API que simplesmente todas as requisições ficam como Pending: provisional headers are shown

Eu fiz todas as possibilidades desse post: https://stackoverflow.com/questions/21177387/caution-provisional-headers-are-shown-in-chrome-debugger

Creio que seja algo relacionado ao dev container ou os containers em sí, se eu faço rebuild do container ele volta a funcionar algumas vezes, é um erro meio "aletório".

**Comment by iaurg** [comment]
Isolei totalmente o app deixando apenas uma rota de test no front e no back, para poder eliminar qualquer possibilidade de erro das nossas implementações e mesmo assim o erro persistiu.

O servidor responde normalmente para requisições feitas via postman/insomnia ou direto pelo console do navegador.

O front também consegue fazer requisição para outras API's normalmente, testei uma requisição para a API do Github.

Parece ser um problema específico de requisição entre o server e front local, quando os dois interagem.

**Comment by iaurg** [comment]
Criei uma branch removendo o dev container e simplificando os dockerfile para testar: https://github.com/iaurg/42-transcendence/tree/fix/promise-pending

Aparentemente resolveu, os erros de conexão não são mais "engolidos" pelo limbo e retornam corretamente quando travam na aba network do browser.

Essa visão expôs alguns erros do server de tratativa de exceptions.

Vou testar mais para ver se não é um falso positivo.

**Comment by vcwild** [comment]
is this solved? @iaurg

**Comment by iaurg** [comment]
Resolvido removendo o dev containers.
